# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PucCompanion < Formula
  desc "Competitive programming companion CLI"
  homepage "https://github.com/tomytp/icpc-companion"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomytp/icpc-companion/releases/download/v1.0.2/puc-companion_1.0.2_darwin_amd64.tar.gz"
      sha256 "c9dd130fba8a074a601f3a9c675cba8fafbcb53a312b037c6ef6ae8e093b8842"

      def install
        bin.install "comp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomytp/icpc-companion/releases/download/v1.0.2/puc-companion_1.0.2_darwin_arm64.tar.gz"
      sha256 "383cc5ea2a812684276ac384a29ed442d6721b56f2fcfe0772e433a9cec01aad"

      def install
        bin.install "comp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomytp/icpc-companion/releases/download/v1.0.2/puc-companion_1.0.2_linux_amd64.tar.gz"
      sha256 "72bc25bb6fc14de52c3628128f4944ed9612f40ff2c79ec7e09936a8512a57ec"
      def install
        bin.install "comp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomytp/icpc-companion/releases/download/v1.0.2/puc-companion_1.0.2_linux_arm64.tar.gz"
      sha256 "f9e0661efc3503d5239574ebe61f885f653e52144db8aab7096eb9ff51ab2087"
      def install
        bin.install "comp"
      end
    end
  end

  test do
    system "#{bin}/comp", "--help"
  end
end
