# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PucCompanion < Formula
  desc "Competitive programming companion CLI"
  homepage "https://github.com/tomytp/icpc-companion"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomytp/icpc-companion/releases/download/v1.0.1/puc-companion_1.0.1_darwin_amd64.tar.gz"
      sha256 "d8414478a7a931411cd8f66098d84844fc5a23ba8a0c6e8db68eaebc8fe42229"

      def install
        bin.install "comp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomytp/icpc-companion/releases/download/v1.0.1/puc-companion_1.0.1_darwin_arm64.tar.gz"
      sha256 "262ccfcb4cb606e0371a153b45f91f32a7eba681458ed11892afdad418d360f5"

      def install
        bin.install "comp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomytp/icpc-companion/releases/download/v1.0.1/puc-companion_1.0.1_linux_amd64.tar.gz"
      sha256 "2d8af263bb5bea1897b4c7c1293a12d372948fa4445bf61201d8b3f7d5efa753"
      def install
        bin.install "comp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomytp/icpc-companion/releases/download/v1.0.1/puc-companion_1.0.1_linux_arm64.tar.gz"
      sha256 "2281645c7d126d824a1ebe642561500118e43ddc93e09c313c750071ee56a9f8"
      def install
        bin.install "comp"
      end
    end
  end

  test do
    system "#{bin}/comp", "--help"
  end
end
