# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PucCompanion < Formula
  desc "Competitive programming companion CLI"
  homepage "https://github.com/tomytp/icpc-companion"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomytp/icpc-companion/releases/download/v1.0.0/puc-companion_1.0.0_darwin_amd64.tar.gz"
      sha256 "e3da2c8f9682a286e87498d8a7e98dfe426eded5ae54f0fdb149ef2d0f775107"

      def install
        bin.install "comp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomytp/icpc-companion/releases/download/v1.0.0/puc-companion_1.0.0_darwin_arm64.tar.gz"
      sha256 "99ba87f0257bed228295b0758a1413600a4f9cc92e050773cd7f3b46a52e6da8"

      def install
        bin.install "comp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomytp/icpc-companion/releases/download/v1.0.0/puc-companion_1.0.0_linux_amd64.tar.gz"
      sha256 "325412f3b8348bc93d7cbb9f6d1b8e42f6d48188af98b4d6affab59855955aa1"
      def install
        bin.install "comp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomytp/icpc-companion/releases/download/v1.0.0/puc-companion_1.0.0_linux_arm64.tar.gz"
      sha256 "b153d3b6e8f2cc713cfd11ea85aac8ba86edb418d7c6a578b54dbdb3e8c43761"
      def install
        bin.install "comp"
      end
    end
  end

  test do
    system "#{bin}/comp", "--help"
  end
end
